cd ../../
export WANDB_DISABLED=true
deepspeed --include="localhost:2,3,4,5,6,7" --master_port=9902 src/train_bash.py \
    --deepspeed /root/huangxin/nanda/llm-moe-merge/config/ds.json \
    --stage pt \
    --flash_attn \
    --model_name_or_path /root/huangxin/nanda/checkpoints/merge/0.5b-bn \
    --small_path /root/huangxin/nanda/checkpoints/merge/0.5b-bn \
    --large_path /root/huangxin/nanda/model/Qwen1.5-7B \
    --every_k_layers_small 3 \
    --every_k_layers_large 4 \
    --seed 22 \
    --max_samples 870561 \
    --do_train \
    --dataset bn \
    --preprocessing_num_workers 64 \
    --cache_dir /mnt/vol1/huangxin/nanda/dataset/CulturaX/cache \
    --cutoff_len 2048 \
    --finetuning_type moea \
    --output_dir /root/huangxin/nanda/checkpoints/merge/0.5b-bn-7b-moea-0.07 \
    --overwrite_output_dir \
    --per_device_train_batch_size 12 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_total_limit 1 \
    --save_only_model \
    --save_steps 200 \
    --learning_rate 2e-4 \
    --num_train_epochs 1.0 \
    --plot_loss \
    --bf16